<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"><?php echo $this->headTitle(''. $this->translate('JobMatch Booking'))->setSeparator(' - ')->setAutoEscape(false) ?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600,700,200italic,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href="/css/style.css" media="screen" rel="stylesheet" type="text/css">
    <link href="/bootstrap-responsive.min.css" media="screen" rel="stylesheet" type="text/css">
    <link href="/css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css">
  </head>

    <body>
   
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->url('home') ?>">&nbsp;&nbsp;&nbsp;<?php echo $this->translate('Rockblings Software Solutions') ?></a>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li class="active"></li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
    
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2012 - <?php echo date('Y') ?> by Rockblings Software Solutions. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
            <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
            <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
            <script src"=/js/bootstrap.min.js"></script>   
            <script src="/js/script.js"></script>
            <script src="/js/js/html5.js"></script>
            
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
